security:
  basic:
    enabled: false # turn off securing our application endpoints

management:
  security:
    enabled: false # turn off securing the actuator endpoints

logging: # <----New sections below
  level:
    io:
      pivotal: INFO

greeting:
  displayFortune: true

quoteServiceURL: http://quote-service-dev.cfapps.io/quote
quoteServiceURLNEW: http://quote-service-dev.cfapps.io/quoteNew
quoteServiceURLNEW2: http://quote-service-dev.cfapps.io/quoteNew2
